//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoTwee.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoTwee.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string configurationWindow_msg_cancel {
            get {
                return ResourceManager.GetString("configurationWindow_msg_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string configurationWindow_msg_configuration {
            get {
                return ResourceManager.GetString("configurationWindow_msg_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string configurationWindow_msg_done {
            get {
                return ResourceManager.GetString("configurationWindow_msg_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of tweet for tune.
        /// </summary>
        internal static string configurationWindow_msg_formatOfTweetForTune {
            get {
                return ResourceManager.GetString("configurationWindow_msg_formatOfTweetForTune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of tweet for tune is wrong..
        /// </summary>
        internal static string configurationWindow_msg_formatOfTweetForTuneIsWrong {
            get {
                return ResourceManager.GetString("configurationWindow_msg_formatOfTweetForTuneIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of tweet for tune with hashtag.
        /// </summary>
        internal static string configurationWindow_msg_formatOfTweetForTuneWithHashTag {
            get {
                return ResourceManager.GetString("configurationWindow_msg_formatOfTweetForTuneWithHashTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of tweet for tune with hashtag is wrong..
        /// </summary>
        internal static string configurationWindow_msg_formatOfTweetForTuneWithHastagIsWrong {
            get {
                return ResourceManager.GetString("configurationWindow_msg_formatOfTweetForTuneWithHastagIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to default.
        /// </summary>
        internal static string configurationWindow_msg_revertToDefault {
            get {
                return ResourceManager.GetString("configurationWindow_msg_revertToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string loginInfoInputWindow_msg_cancel {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate RoTwee.
        /// </summary>
        internal static string loginInfoInputWindow_msg_caption {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate at [Twitter], and input verifier to this window..
        /// </summary>
        internal static string loginInfoInputWindow_msg_description {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed in authentication.
        ///Retry authentication with reopening Twitter page again..
        /// </summary>
        internal static string loginInfoInputWindow_msg_failedToAuthenticate {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_failedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string loginInfoInputWindow_msg_ok {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string newtweetInputWindow_msg_cancel {
            get {
                return ResourceManager.GetString("newtweetInputWindow_msg_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write message.
        /// </summary>
        internal static string newtweetInputWindow_msg_caption {
            get {
                return ResourceManager.GetString("newtweetInputWindow_msg_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string newtweetInputWindow_msg_submit {
            get {
                return ResourceManager.GetString("newtweetInputWindow_msg_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Window x:Class=&quot;RoTwee.TweetsWindow&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    Title=&quot;RoTwee&quot; Height=&quot;300&quot; Width=&quot;300&quot; ResizeMode=&quot;CanResize&quot;  Icon=&quot;rotate.ico&quot; Loaded=&quot;Window_Loaded&quot;&gt;
        ///    &lt;Grid ShowGridLines=&quot;True&quot; Background=&quot;Black&quot; Name=&quot;_grid&quot; 
        ///        MouseDown=&quot;_grid_MouseDown&quot; MouseUp=&quot;_grid_MouseUp&quot; MouseMove=&quot;_grid_MouseMove&quot; MouseWheel=&quot;_grid_MouseWheel&quot;&gt;
        ///        &lt;Button Height=&quot;16&quot; HorizontalAlignmen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TweetsWindow {
            get {
                return ResourceManager.GetString("TweetsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Xml;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///using System.Windows.Media.Animation;
        ///using System.IO;
        ///using System.Net;
        ///using System. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TweetsWindow_xaml {
            get {
                return ResourceManager.GetString("TweetsWindow_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string tweetWindow_msg_accessServer {
            get {
                return ResourceManager.GetString("tweetWindow_msg_accessServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color..
        /// </summary>
        internal static string tweetWindow_msg_changeColor {
            get {
                return ResourceManager.GetString("tweetWindow_msg_changeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to open &quot;{0}&quot;..
        /// </summary>
        internal static string tweetWindow_msg_confirmNavigation {
            get {
                return ResourceManager.GetString("tweetWindow_msg_confirmNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL.
        /// </summary>
        internal static string tweetWindow_msg_confirmNavigationCaption {
            get {
                return ResourceManager.GetString("tweetWindow_msg_confirmNavigationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing no tune..
        /// </summary>
        internal static string tweetWindow_msg_noTune {
            get {
                return ResourceManager.GetString("tweetWindow_msg_noTune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}/{1}/{2}&quot; is playing now..
        /// </summary>
        internal static string tweetWindow_msg_playingTuneTweetFormat {
            get {
                return ResourceManager.GetString("tweetWindow_msg_playingTuneTweetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing &quot;{0}/{1}/{2}&quot; now. #nowplaying.
        /// </summary>
        internal static string tweetWindow_msg_playingTuneTweetWithHashTagFormat {
            get {
                return ResourceManager.GetString("tweetWindow_msg_playingTuneTweetWithHashTagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post playing tune.
        /// </summary>
        internal static string tweetWindow_msg_postPlayingTune {
            get {
                return ResourceManager.GetString("tweetWindow_msg_postPlayingTune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was failed to post playing tune.
        ///This feature needs iTune to be installed on your PC..
        /// </summary>
        internal static string tweetWindow_msg_postPlayingTuneError {
            get {
                return ResourceManager.GetString("tweetWindow_msg_postPlayingTuneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post playing tune with hash tag..
        /// </summary>
        internal static string tweetWindow_msg_postPlayingTuneWithHashTag {
            get {
                return ResourceManager.GetString("tweetWindow_msg_postPlayingTuneWithHashTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post about playing tune..
        /// </summary>
        internal static string tweetWindow_msg_postPlayingTuneWithText {
            get {
                return ResourceManager.GetString("tweetWindow_msg_postPlayingTuneWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post rotated count..
        /// </summary>
        internal static string tweetWindow_msg_postRotateCount {
            get {
                return ResourceManager.GetString("tweetWindow_msg_postRotateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotated {0:f3} times now. #rotatedCount.
        /// </summary>
        internal static string tweetWindow_msg_rotateCountTweetFormat {
            get {
                return ResourceManager.GetString("tweetWindow_msg_rotateCountTweetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed for network error.
        ///RoTwee needs network connection..
        /// </summary>
        internal static string tweetWindow_msg_startupFailedForNetworkError {
            get {
                return ResourceManager.GetString("tweetWindow_msg_startupFailedForNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write message.
        /// </summary>
        internal static string tweetWindow_msg_writeMessage {
            get {
                return ResourceManager.GetString("tweetWindow_msg_writeMessage", resourceCulture);
            }
        }
    }
}
