//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4200
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoTwee.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoTwee.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string loginInfoInputWindow_msg_cancel {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RotWeeを認可する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string loginInfoInputWindow_msg_caption {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ついったーのページ]で認可したのち、返された値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string loginInfoInputWindow_msg_description {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認可に失敗しました。
        ///ついったーのページをリンクより開ける所からやり直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string loginInfoInputWindow_msg_failedToAuthenticate {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_failedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string loginInfoInputWindow_msg_ok {
            get {
                return ResourceManager.GetString("loginInfoInputWindow_msg_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string newtweetInputWindow_msg_cancel {
            get {
                return ResourceManager.GetString("newtweetInputWindow_msg_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string newtweetInputWindow_msg_caption {
            get {
                return ResourceManager.GetString("newtweetInputWindow_msg_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き込む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string newtweetInputWindow_msg_submit {
            get {
                return ResourceManager.GetString("newtweetInputWindow_msg_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tweetWindow_msg_accessServer {
            get {
                return ResourceManager.GetString("tweetWindow_msg_accessServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントを書き込む。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tweetWindow_msg_writeMessage {
            get {
                return ResourceManager.GetString("tweetWindow_msg_writeMessage", resourceCulture);
            }
        }
    }
}
